[package]
name = "AftermathRouter"
version = "0.0.1"
published-at = "0xefe170ec0be4d762196bedecd7a065816576198a6527c99282a2551aaa7da38c"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.19.1" }
DeepBook = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/deepbook", rev = "mainnet-v1.19.1" }
AftermathSwapCap = { local = "../swap-cap" }

[addresses]
aftermath_router = "0xf63c58d762286cff1ef8eab36a24c836d23ec0ca19eacbafec7a0275a09cd520"
deepbook =  "000000000000000000000000000000000000000000000000000000000000dee9"